apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: node_aug_12
  janus-idp.io/tekton: node_aug_12
  backstage.io/kubernetes-id: node_aug_12
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: node_aug_12
resources:
- deployment.yaml
- route.yaml
- service.yaml
