apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: node_aug_12
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node_aug_12 
  name: node_aug_12
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: node_aug_12
    weight: 100 
